spring.application.name=spring-Security-proj

spring.datasource.url = jdbc:mysql://localhost:3306/security

spring.datasource.username = root
spring.datasource.password = naman123
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update


spring.security.user.name= Naman
spring.security.user.password= naman123